---
- name: install MySQL(mariaDB)
  yum: name={{ item }}  state=latest
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel

- name: enable mariaDB service
  service: name=mariadb enabled=yes

- name: start mariaDB service
  service: name=mariadb state=started
